[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shared"
version = "1.0.0"
dependencies = ["pydantic"]

[tool.setuptools.packages.find]
where = ["src"]